export const PATH = {
  MAIN: '/',
  LOG_UP: '/log-up',
  LOG_IN: '/log-in',
  PASS_RECOVERY: '/password',
  SET_NEW_PASS: '/set-new-password/:token',
  CHECK_EMAIL: '/check-email',
  PROFILE: '/profile',
  PACKS: '/packs/',
  MY_PACKS: '/my-packs',
  CARDS: '/cards',
  LEARN_CARDS: '/learn',
  ERROR_404: '/404',
  NOT_FOUND: '/*',
} as const
